name: Continuous integration example (Parametrizado)

on: 
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    # 1. Definimos la matriz de parámetros
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: ['17', '21']
      # Opcional: fail-fast en false permite que si falla uno, los demás sigan
      fail-fast: false

    # 2. Usamos el parámetro del runner
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4 # Nota: La versión estable actual es v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          # 3. Usamos el parámetro de la versión de Java
          java-version: ${{ matrix.java-version }}
          cache: 'maven'

      - name: Run tests
        run: mvn test